version: '3.8'

services:
  ethereum-node1:
    build: .
    container_name: ethereum-node1
    ports:
      - "30303:30303"
      - "8545:8545"
    volumes:
      - node1-data:/root/.ethereum

  ethereum-node2:
    build: .
    container_name: ethereum-node2
    ports:
      - "30304:30303"
      - "8546:8545"
    volumes:
      - node2-data:/root/.ethereum

volumes:
  node1-data:
  node2-data:
